### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by pi43r** [valiafetisov/unkwn#1]
Hi,
I created an api key and put it with the website in the settings.json – Then I installed the extension. 
When I open my feed I don't see anything. What am I supposed to see?

**Comment by valiafetisov** [comment]
Hello @astreinerBaum, i've just recreate apikey and it works as expected. I've added a screenshot to the readme, to illustrate how it looks like. Nothing fancy.

If you have troubles running it, please check that you putted the right gateway url into settings.json (should be `https://gateway-a.watsonplatform.net/calls/text/TextGetEmotion`) and check your browser console for errors, while browsing Facebook.

**Comment by pi43r** [comment]
Thank you. 

changing
`https://gateway-a.watsonplatform.net/calls`
to
`https://gateway-a.watsonplatform.net/calls/text/TextGetEmotion`
did the trick for me. 
I don't know why some posts get analyzed and others won't.

**Comment by valiafetisov** [comment]
That's possible for posts without any comments like link shares or videos, which are not analysed by the moment.

Anyway the subject is resolved, so i'm closing this issue.
